---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - openssl aes-256-cbc -K $encrypted_bdf29e24ac6e_key -iv $encrypted_bdf29e24ac6e_iv -in clouds.yml.enc -out clouds.yml -d

install:
  - pip install -r requirements.txt

script:
  - scripts/validate.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    use_notice: true
